#pragma once
#include <easy2d/easy2d.h>
using namespace easy2d;

easy2d::Sprite* playerShip1_damage1;
easy2d::Sprite* playerShip1_damage2;
easy2d::Sprite* playerShip1_damage3;
easy2d::Sprite* playerShip2_damage1;
easy2d::Sprite* playerShip2_damage2;
easy2d::Sprite* playerShip2_damage3;
easy2d::Sprite* playerShip3_damage1;
easy2d::Sprite* playerShip3_damage2;
easy2d::Sprite* playerShip3_damage3;
easy2d::Sprite* fire00;
easy2d::Sprite* fire01;
easy2d::Sprite* fire02;
easy2d::Sprite* fire03;
easy2d::Sprite* fire04;
easy2d::Sprite* fire05;
easy2d::Sprite* fire06;
easy2d::Sprite* fire07;
easy2d::Sprite* fire08;
easy2d::Sprite* fire09;
easy2d::Sprite* fire10;
easy2d::Sprite* fire11;
easy2d::Sprite* fire12;
easy2d::Sprite* fire13;
easy2d::Sprite* fire14;
easy2d::Sprite* fire15;
easy2d::Sprite* fire16;
easy2d::Sprite* fire17;
easy2d::Sprite* fire18;
easy2d::Sprite* fire19;
easy2d::Sprite* shield1;
easy2d::Sprite* shield2;
easy2d::Sprite* shield3;
easy2d::Sprite* speed;
easy2d::Sprite* star1;
easy2d::Sprite* star2;
easy2d::Sprite* star3;
easy2d::Sprite* enemyBlack1;
easy2d::Sprite* enemyBlack2;
easy2d::Sprite* enemyBlack3;
easy2d::Sprite* enemyBlack4;
easy2d::Sprite* enemyBlack5;
easy2d::Sprite* enemyBlue1;
easy2d::Sprite* enemyBlue2;
easy2d::Sprite* enemyBlue3;
easy2d::Sprite* enemyBlue4;
easy2d::Sprite* enemyBlue5;
easy2d::Sprite* enemyGreen1;
easy2d::Sprite* enemyGreen2;
easy2d::Sprite* enemyGreen3;
easy2d::Sprite* enemyGreen4;
easy2d::Sprite* enemyGreen5;
easy2d::Sprite* enemyRed1;
easy2d::Sprite* enemyRed2;
easy2d::Sprite* enemyRed3;
easy2d::Sprite* enemyRed4;
easy2d::Sprite* enemyRed5;
easy2d::Sprite* laserBlue01;
easy2d::Sprite* laserBlue02;
easy2d::Sprite* laserBlue03;
easy2d::Sprite* laserBlue04;
easy2d::Sprite* laserBlue05;
easy2d::Sprite* laserBlue06;
easy2d::Sprite* laserBlue07;
easy2d::Sprite* laserBlue08;
easy2d::Sprite* laserBlue09;
easy2d::Sprite* laserBlue10;
easy2d::Sprite* laserBlue11;
easy2d::Sprite* laserBlue12;
easy2d::Sprite* laserBlue13;
easy2d::Sprite* laserBlue14;
easy2d::Sprite* laserBlue15;
easy2d::Sprite* laserBlue16;
easy2d::Sprite* laserGreen01;
easy2d::Sprite* laserGreen02;
easy2d::Sprite* laserGreen03;
easy2d::Sprite* laserGreen04;
easy2d::Sprite* laserGreen05;
easy2d::Sprite* laserGreen06;
easy2d::Sprite* laserGreen07;
easy2d::Sprite* laserGreen08;
easy2d::Sprite* laserGreen09;
easy2d::Sprite* laserGreen10;
easy2d::Sprite* laserGreen11;
easy2d::Sprite* laserGreen12;
easy2d::Sprite* laserGreen13;
easy2d::Sprite* laserGreen14;
easy2d::Sprite* laserGreen15;
easy2d::Sprite* laserGreen16;
easy2d::Sprite* laserRed01;
easy2d::Sprite* laserRed02;
easy2d::Sprite* laserRed03;
easy2d::Sprite* laserRed04;
easy2d::Sprite* laserRed05;
easy2d::Sprite* laserRed06;
easy2d::Sprite* laserRed07;
easy2d::Sprite* laserRed08;
easy2d::Sprite* laserRed09;
easy2d::Sprite* laserRed10;
easy2d::Sprite* laserRed11;
easy2d::Sprite* laserRed12;
easy2d::Sprite* laserRed13;
easy2d::Sprite* laserRed14;
easy2d::Sprite* laserRed15;
easy2d::Sprite* laserRed16;
easy2d::Sprite* meteorBrown_big1;
easy2d::Sprite* meteorBrown_big2;
easy2d::Sprite* meteorBrown_big3;
easy2d::Sprite* meteorBrown_big4;
easy2d::Sprite* meteorBrown_med1;
easy2d::Sprite* meteorBrown_med3;
easy2d::Sprite* meteorBrown_small1;
easy2d::Sprite* meteorBrown_small2;
easy2d::Sprite* meteorBrown_tiny1;
easy2d::Sprite* meteorBrown_tiny2;
easy2d::Sprite* meteorGrey_big1;
easy2d::Sprite* meteorGrey_big2;
easy2d::Sprite* meteorGrey_big3;
easy2d::Sprite* meteorGrey_big4;
easy2d::Sprite* meteorGrey_med1;
easy2d::Sprite* meteorGrey_med2;
easy2d::Sprite* meteorGrey_small1;
easy2d::Sprite* meteorGrey_small2;
easy2d::Sprite* meteorGrey_tiny1;
easy2d::Sprite* meteorGrey_tiny2;
easy2d::Sprite* beam0;
easy2d::Sprite* beam1;
easy2d::Sprite* beam2;
easy2d::Sprite* beam3;
easy2d::Sprite* beam4;
easy2d::Sprite* beam5;
easy2d::Sprite* beam6;
easy2d::Sprite* beamLong1;
easy2d::Sprite* beamLong2;
easy2d::Sprite* cockpitBlue_0;
easy2d::Sprite* cockpitBlue_1;
easy2d::Sprite* cockpitBlue_2;
easy2d::Sprite* cockpitBlue_3;
easy2d::Sprite* cockpitBlue_4;
easy2d::Sprite* cockpitBlue_5;
easy2d::Sprite* cockpitBlue_6;
easy2d::Sprite* cockpitBlue_7;
easy2d::Sprite* cockpitGreen_0;
easy2d::Sprite* cockpitGreen_1;
easy2d::Sprite* cockpitGreen_2;
easy2d::Sprite* cockpitGreen_3;
easy2d::Sprite* cockpitGreen_4;
easy2d::Sprite* cockpitGreen_5;
easy2d::Sprite* cockpitGreen_6;
easy2d::Sprite* cockpitGreen_7;
easy2d::Sprite* cockpitRed_0;
easy2d::Sprite* cockpitRed_1;
easy2d::Sprite* cockpitRed_2;
easy2d::Sprite* cockpitRed_3;
easy2d::Sprite* cockpitRed_4;
easy2d::Sprite* cockpitRed_5;
easy2d::Sprite* cockpitRed_6;
easy2d::Sprite* cockpitRed_7;
easy2d::Sprite* cockpitYellow_0;
easy2d::Sprite* cockpitYellow_1;
easy2d::Sprite* cockpitYellow_2;
easy2d::Sprite* cockpitYellow_3;
easy2d::Sprite* cockpitYellow_4;
easy2d::Sprite* cockpitYellow_5;
easy2d::Sprite* cockpitYellow_6;
easy2d::Sprite* cockpitYellow_7;
easy2d::Sprite* engine1;
easy2d::Sprite* engine2;
easy2d::Sprite* engine3;
easy2d::Sprite* engine4;
easy2d::Sprite* engine5;
easy2d::Sprite* gun00;
easy2d::Sprite* gun01;
easy2d::Sprite* gun02;
easy2d::Sprite* gun03;
easy2d::Sprite* gun04;
easy2d::Sprite* gun05;
easy2d::Sprite* gun06;
easy2d::Sprite* gun07;
easy2d::Sprite* gun08;
easy2d::Sprite* gun09;
easy2d::Sprite* gun10;
easy2d::Sprite* scratch1;
easy2d::Sprite* scratch2;
easy2d::Sprite* scratch3;
easy2d::Sprite* turretBase_big;
easy2d::Sprite* turretBase_small;
easy2d::Sprite* wingBlue_0;
easy2d::Sprite* wingBlue_1;
easy2d::Sprite* wingBlue_2;
easy2d::Sprite* wingBlue_3;
easy2d::Sprite* wingBlue_4;
easy2d::Sprite* wingBlue_5;
easy2d::Sprite* wingBlue_6;
easy2d::Sprite* wingBlue_7;
easy2d::Sprite* wingGreen_0;
easy2d::Sprite* wingGreen_1;
easy2d::Sprite* wingGreen_2;
easy2d::Sprite* wingGreen_3;
easy2d::Sprite* wingGreen_4;
easy2d::Sprite* wingGreen_5;
easy2d::Sprite* wingGreen_6;
easy2d::Sprite* wingGreen_7;
easy2d::Sprite* wingRed_0;
easy2d::Sprite* wingRed_1;
easy2d::Sprite* wingRed_2;
easy2d::Sprite* wingRed_3;
easy2d::Sprite* wingRed_4;
easy2d::Sprite* wingRed_5;
easy2d::Sprite* wingRed_6;
easy2d::Sprite* wingRed_7;
easy2d::Sprite* wingYellow_0;
easy2d::Sprite* wingYellow_1;
easy2d::Sprite* wingYellow_2;
easy2d::Sprite* wingYellow_3;
easy2d::Sprite* wingYellow_4;
easy2d::Sprite* wingYellow_5;
easy2d::Sprite* wingYellow_6;
easy2d::Sprite* wingYellow_7;
easy2d::Sprite* playerShip1_blue;
easy2d::Sprite* playerShip1_green;
easy2d::Sprite* playerShip1_orange;
easy2d::Sprite* playerShip1_red;
easy2d::Sprite* playerShip2_blue;
easy2d::Sprite* playerShip2_green;
easy2d::Sprite* playerShip2_orange;
easy2d::Sprite* playerShip2_red;
easy2d::Sprite* playerShip3_blue;
easy2d::Sprite* playerShip3_green;
easy2d::Sprite* playerShip3_orange;
easy2d::Sprite* playerShip3_red;
easy2d::Sprite* bold_silver;
easy2d::Sprite* bolt_bronze;
easy2d::Sprite* bolt_gold;
easy2d::Sprite* pill_blue;
easy2d::Sprite* pill_green;
easy2d::Sprite* pill_red;
easy2d::Sprite* pill_yellow;
easy2d::Sprite* powerupBlue;
easy2d::Sprite* powerupBlue_bolt;
easy2d::Sprite* powerupBlue_shield;
easy2d::Sprite* powerupBlue_star;
easy2d::Sprite* powerupGreen;
easy2d::Sprite* powerupGreen_bolt;
easy2d::Sprite* powerupGreen_shield;
easy2d::Sprite* powerupGreen_star;
easy2d::Sprite* powerupRed;
easy2d::Sprite* powerupRed_bolt;
easy2d::Sprite* powerupRed_shield;
easy2d::Sprite* powerupRed_star;
easy2d::Sprite* powerupYellow;
easy2d::Sprite* powerupYellow_bolt;
easy2d::Sprite* powerupYellow_shield;
easy2d::Sprite* powerupYellow_star;
easy2d::Sprite* shield_bronze;
easy2d::Sprite* shield_gold;
easy2d::Sprite* shield_silver;
easy2d::Sprite* star_bronze;
easy2d::Sprite* star_gold;
easy2d::Sprite* star_silver;
easy2d::Sprite* things_bronze;
easy2d::Sprite* things_gold;
easy2d::Sprite* things_silver;
easy2d::Sprite* ufoBlue;
easy2d::Sprite* ufoGreen;
easy2d::Sprite* ufoRed;
easy2d::Sprite* ufoYellow;
easy2d::Sprite* aim;
easy2d::Sprite* buttonBlue;
easy2d::Sprite* buttonGreen;
easy2d::Sprite* buttonRed;
easy2d::Sprite* buttonYellow;
easy2d::Sprite* cursor;
easy2d::Sprite* numeral0;
easy2d::Sprite* numeral1;
easy2d::Sprite* numeral2;
easy2d::Sprite* numeral3;
easy2d::Sprite* numeral4;
easy2d::Sprite* numeral5;
easy2d::Sprite* numeral6;
easy2d::Sprite* numeral7;
easy2d::Sprite* numeral8;
easy2d::Sprite* numeral9;
easy2d::Sprite* numeralX;
easy2d::Sprite* playerLife1_blue;
easy2d::Sprite* playerLife1_green;
easy2d::Sprite* playerLife1_orange;
easy2d::Sprite* playerLife1_red;
easy2d::Sprite* playerLife2_blue;
easy2d::Sprite* playerLife2_green;
easy2d::Sprite* playerLife2_orange;
easy2d::Sprite* playerLife2_red;
easy2d::Sprite* playerLife3_blue;
easy2d::Sprite* playerLife3_green;
easy2d::Sprite* playerLife3_orange;
easy2d::Sprite* playerLife3_red;
easy2d::Sprite* particle1_blue;
easy2d::Sprite* particle1_green;
easy2d::Sprite* particle1_red;
easy2d::Sprite* particle1_white;
easy2d::Sprite* particle1_yellow;

easy2d::Sequence* action_particle1; // 基本粒子动画（轨迹）
easy2d::Sequence* action_particle2; // 基本粒子动画（航迹）
easy2d::Sequence* action_particle3; // 基本粒子动画（引擎）

void ActionInit()
{
    auto scaleTo = gcnew ScaleTo(0.8, 0.0f);
    auto opacityTo = gcnew OpacityTo(0.8, 0.0f);
    auto two = gcnew Spawn({ scaleTo, opacityTo });
    scaleTo = gcnew ScaleTo(0, 0.1f);
    action_particle1 = gcnew Sequence({ scaleTo, two });
    action_particle1->retain();

    scaleTo = gcnew ScaleTo(0.5f, 0.12f);
    opacityTo = gcnew OpacityTo(0.4f, 0.0f);
    two = gcnew Spawn({ scaleTo, opacityTo });
    scaleTo = gcnew ScaleTo(0, 0.5f);
    action_particle2 = gcnew Sequence({ scaleTo, two });
    action_particle2->retain();

    scaleTo = gcnew ScaleTo(0.4f, 0.15f);
    opacityTo = gcnew OpacityTo(0.4f, 0.0f);
    two = gcnew Spawn({ scaleTo, opacityTo });
    scaleTo = gcnew ScaleTo(0, 0.4f);
    action_particle3 = gcnew Sequence({ scaleTo, two });
    action_particle3->retain();
}

void GameInit()
{
    ActionInit();
    easy2d::MusicPlayer::preload("./Bonus/sfx_laser1.wav");
    easy2d::MusicPlayer::preload("./Bonus/sfx_laser2.wav");
    easy2d::MusicPlayer::preload("./Bonus/sfx_lose.wav");
    easy2d::MusicPlayer::preload("./Bonus/sfx_shieldDown.wav");
    easy2d::MusicPlayer::preload("./Bonus/sfx_shieldUp.wav");
    easy2d::MusicPlayer::preload("./Bonus/sfx_twoTone.wav");
    easy2d::MusicPlayer::preload("./Bonus/sfx_zap.wav");
    playerShip1_damage1 = gcnew Sprite("./PNG/Damage/playerShip1_damage1.png"); playerShip1_damage1->retain();
    playerShip1_damage2 = gcnew Sprite("./PNG/Damage/playerShip1_damage2.png"); playerShip1_damage2->retain();
    playerShip1_damage3 = gcnew Sprite("./PNG/Damage/playerShip1_damage3.png"); playerShip1_damage3->retain();
    playerShip2_damage1 = gcnew Sprite("./PNG/Damage/playerShip2_damage1.png"); playerShip2_damage1->retain();
    playerShip2_damage2 = gcnew Sprite("./PNG/Damage/playerShip2_damage2.png"); playerShip2_damage2->retain();
    playerShip2_damage3 = gcnew Sprite("./PNG/Damage/playerShip2_damage3.png"); playerShip2_damage3->retain();
    playerShip3_damage1 = gcnew Sprite("./PNG/Damage/playerShip3_damage1.png"); playerShip3_damage1->retain();
    playerShip3_damage2 = gcnew Sprite("./PNG/Damage/playerShip3_damage2.png"); playerShip3_damage2->retain();
    playerShip3_damage3 = gcnew Sprite("./PNG/Damage/playerShip3_damage3.png"); playerShip3_damage3->retain();
    fire00 = gcnew Sprite("./PNG/Effects/fire00.png"); fire00->retain();
    fire01 = gcnew Sprite("./PNG/Effects/fire01.png"); fire01->retain();
    fire02 = gcnew Sprite("./PNG/Effects/fire02.png"); fire02->retain();
    fire03 = gcnew Sprite("./PNG/Effects/fire03.png"); fire03->retain();
    fire04 = gcnew Sprite("./PNG/Effects/fire04.png"); fire04->retain();
    fire05 = gcnew Sprite("./PNG/Effects/fire05.png"); fire05->retain();
    fire06 = gcnew Sprite("./PNG/Effects/fire06.png"); fire06->retain();
    fire07 = gcnew Sprite("./PNG/Effects/fire07.png"); fire07->retain();
    fire08 = gcnew Sprite("./PNG/Effects/fire08.png"); fire08->retain();
    fire09 = gcnew Sprite("./PNG/Effects/fire09.png"); fire09->retain();
    fire10 = gcnew Sprite("./PNG/Effects/fire10.png"); fire10->retain();
    fire11 = gcnew Sprite("./PNG/Effects/fire11.png"); fire11->retain();
    fire12 = gcnew Sprite("./PNG/Effects/fire12.png"); fire12->retain();
    fire13 = gcnew Sprite("./PNG/Effects/fire13.png"); fire13->retain();
    fire14 = gcnew Sprite("./PNG/Effects/fire14.png"); fire14->retain();
    fire15 = gcnew Sprite("./PNG/Effects/fire15.png"); fire15->retain();
    fire16 = gcnew Sprite("./PNG/Effects/fire16.png"); fire16->retain();
    fire17 = gcnew Sprite("./PNG/Effects/fire17.png"); fire17->retain();
    fire18 = gcnew Sprite("./PNG/Effects/fire18.png"); fire18->retain();
    fire19 = gcnew Sprite("./PNG/Effects/fire19.png"); fire19->retain();
    shield1 = gcnew Sprite("./PNG/Effects/shield1.png"); shield1->retain();
    shield2 = gcnew Sprite("./PNG/Effects/shield2.png"); shield2->retain();
    shield3 = gcnew Sprite("./PNG/Effects/shield3.png"); shield3->retain();
    speed = gcnew Sprite("./PNG/Effects/speed.png"); speed->retain();
    star1 = gcnew Sprite("./PNG/Effects/star1.png"); star1->retain();
    star2 = gcnew Sprite("./PNG/Effects/star2.png"); star2->retain();
    star3 = gcnew Sprite("./PNG/Effects/star3.png"); star3->retain();
    enemyBlack1 = gcnew Sprite("./PNG/Enemies/enemyBlack1.png"); enemyBlack1->retain();
    enemyBlack2 = gcnew Sprite("./PNG/Enemies/enemyBlack2.png"); enemyBlack2->retain();
    enemyBlack3 = gcnew Sprite("./PNG/Enemies/enemyBlack3.png"); enemyBlack3->retain();
    enemyBlack4 = gcnew Sprite("./PNG/Enemies/enemyBlack4.png"); enemyBlack4->retain();
    enemyBlack5 = gcnew Sprite("./PNG/Enemies/enemyBlack5.png"); enemyBlack5->retain();
    enemyBlue1 = gcnew Sprite("./PNG/Enemies/enemyBlue1.png"); enemyBlue1->retain();
    enemyBlue2 = gcnew Sprite("./PNG/Enemies/enemyBlue2.png"); enemyBlue2->retain();
    enemyBlue3 = gcnew Sprite("./PNG/Enemies/enemyBlue3.png"); enemyBlue3->retain();
    enemyBlue4 = gcnew Sprite("./PNG/Enemies/enemyBlue4.png"); enemyBlue4->retain();
    enemyBlue5 = gcnew Sprite("./PNG/Enemies/enemyBlue5.png"); enemyBlue5->retain();
    enemyGreen1 = gcnew Sprite("./PNG/Enemies/enemyGreen1.png"); enemyGreen1->retain();
    enemyGreen2 = gcnew Sprite("./PNG/Enemies/enemyGreen2.png"); enemyGreen2->retain();
    enemyGreen3 = gcnew Sprite("./PNG/Enemies/enemyGreen3.png"); enemyGreen3->retain();
    enemyGreen4 = gcnew Sprite("./PNG/Enemies/enemyGreen4.png"); enemyGreen4->retain();
    enemyGreen5 = gcnew Sprite("./PNG/Enemies/enemyGreen5.png"); enemyGreen5->retain();
    enemyRed1 = gcnew Sprite("./PNG/Enemies/enemyRed1.png"); enemyRed1->retain();
    enemyRed2 = gcnew Sprite("./PNG/Enemies/enemyRed2.png"); enemyRed2->retain();
    enemyRed3 = gcnew Sprite("./PNG/Enemies/enemyRed3.png"); enemyRed3->retain();
    enemyRed4 = gcnew Sprite("./PNG/Enemies/enemyRed4.png"); enemyRed4->retain();
    enemyRed5 = gcnew Sprite("./PNG/Enemies/enemyRed5.png"); enemyRed5->retain();
    laserBlue01 = gcnew Sprite("./PNG/Lasers/laserBlue01.png"); laserBlue01->retain();
    laserBlue02 = gcnew Sprite("./PNG/Lasers/laserBlue02.png"); laserBlue02->retain();
    laserBlue03 = gcnew Sprite("./PNG/Lasers/laserBlue03.png"); laserBlue03->retain();
    laserBlue04 = gcnew Sprite("./PNG/Lasers/laserBlue04.png"); laserBlue04->retain();
    laserBlue05 = gcnew Sprite("./PNG/Lasers/laserBlue05.png"); laserBlue05->retain();
    laserBlue06 = gcnew Sprite("./PNG/Lasers/laserBlue06.png"); laserBlue06->retain();
    laserBlue07 = gcnew Sprite("./PNG/Lasers/laserBlue07.png"); laserBlue07->retain();
    laserBlue08 = gcnew Sprite("./PNG/Lasers/laserBlue08.png"); laserBlue08->retain();
    laserBlue09 = gcnew Sprite("./PNG/Lasers/laserBlue09.png"); laserBlue09->retain();
    laserBlue10 = gcnew Sprite("./PNG/Lasers/laserBlue10.png"); laserBlue10->retain();
    laserBlue11 = gcnew Sprite("./PNG/Lasers/laserBlue11.png"); laserBlue11->retain();
    laserBlue12 = gcnew Sprite("./PNG/Lasers/laserBlue12.png"); laserBlue12->retain();
    laserBlue13 = gcnew Sprite("./PNG/Lasers/laserBlue13.png"); laserBlue13->retain();
    laserBlue14 = gcnew Sprite("./PNG/Lasers/laserBlue14.png"); laserBlue14->retain();
    laserBlue15 = gcnew Sprite("./PNG/Lasers/laserBlue15.png"); laserBlue15->retain();
    laserBlue16 = gcnew Sprite("./PNG/Lasers/laserBlue16.png"); laserBlue16->retain();
    laserGreen01 = gcnew Sprite("./PNG/Lasers/laserGreen01.png"); laserGreen01->retain();
    laserGreen02 = gcnew Sprite("./PNG/Lasers/laserGreen02.png"); laserGreen02->retain();
    laserGreen03 = gcnew Sprite("./PNG/Lasers/laserGreen03.png"); laserGreen03->retain();
    laserGreen04 = gcnew Sprite("./PNG/Lasers/laserGreen04.png"); laserGreen04->retain();
    laserGreen05 = gcnew Sprite("./PNG/Lasers/laserGreen05.png"); laserGreen05->retain();
    laserGreen06 = gcnew Sprite("./PNG/Lasers/laserGreen06.png"); laserGreen06->retain();
    laserGreen07 = gcnew Sprite("./PNG/Lasers/laserGreen07.png"); laserGreen07->retain();
    laserGreen08 = gcnew Sprite("./PNG/Lasers/laserGreen08.png"); laserGreen08->retain();
    laserGreen09 = gcnew Sprite("./PNG/Lasers/laserGreen09.png"); laserGreen09->retain();
    laserGreen10 = gcnew Sprite("./PNG/Lasers/laserGreen10.png"); laserGreen10->retain();
    laserGreen11 = gcnew Sprite("./PNG/Lasers/laserGreen11.png"); laserGreen11->retain();
    laserGreen12 = gcnew Sprite("./PNG/Lasers/laserGreen12.png"); laserGreen12->retain();
    laserGreen13 = gcnew Sprite("./PNG/Lasers/laserGreen13.png"); laserGreen13->retain();
    laserGreen14 = gcnew Sprite("./PNG/Lasers/laserGreen14.png"); laserGreen14->retain();
    laserGreen15 = gcnew Sprite("./PNG/Lasers/laserGreen15.png"); laserGreen15->retain();
    laserGreen16 = gcnew Sprite("./PNG/Lasers/laserGreen16.png"); laserGreen16->retain();
    laserRed01 = gcnew Sprite("./PNG/Lasers/laserRed01.png"); laserRed01->retain();
    laserRed02 = gcnew Sprite("./PNG/Lasers/laserRed02.png"); laserRed02->retain();
    laserRed03 = gcnew Sprite("./PNG/Lasers/laserRed03.png"); laserRed03->retain();
    laserRed04 = gcnew Sprite("./PNG/Lasers/laserRed04.png"); laserRed04->retain();
    laserRed05 = gcnew Sprite("./PNG/Lasers/laserRed05.png"); laserRed05->retain();
    laserRed06 = gcnew Sprite("./PNG/Lasers/laserRed06.png"); laserRed06->retain();
    laserRed07 = gcnew Sprite("./PNG/Lasers/laserRed07.png"); laserRed07->retain();
    laserRed08 = gcnew Sprite("./PNG/Lasers/laserRed08.png"); laserRed08->retain();
    laserRed09 = gcnew Sprite("./PNG/Lasers/laserRed09.png"); laserRed09->retain();
    laserRed10 = gcnew Sprite("./PNG/Lasers/laserRed10.png"); laserRed10->retain();
    laserRed11 = gcnew Sprite("./PNG/Lasers/laserRed11.png"); laserRed11->retain();
    laserRed12 = gcnew Sprite("./PNG/Lasers/laserRed12.png"); laserRed12->retain();
    laserRed13 = gcnew Sprite("./PNG/Lasers/laserRed13.png"); laserRed13->retain();
    laserRed14 = gcnew Sprite("./PNG/Lasers/laserRed14.png"); laserRed14->retain();
    laserRed15 = gcnew Sprite("./PNG/Lasers/laserRed15.png"); laserRed15->retain();
    laserRed16 = gcnew Sprite("./PNG/Lasers/laserRed16.png"); laserRed16->retain();
    meteorBrown_big1 = gcnew Sprite("./PNG/Meteors/meteorBrown_big1.png"); meteorBrown_big1->retain();
    meteorBrown_big2 = gcnew Sprite("./PNG/Meteors/meteorBrown_big2.png"); meteorBrown_big2->retain();
    meteorBrown_big3 = gcnew Sprite("./PNG/Meteors/meteorBrown_big3.png"); meteorBrown_big3->retain();
    meteorBrown_big4 = gcnew Sprite("./PNG/Meteors/meteorBrown_big4.png"); meteorBrown_big4->retain();
    meteorBrown_med1 = gcnew Sprite("./PNG/Meteors/meteorBrown_med1.png"); meteorBrown_med1->retain();
    meteorBrown_med3 = gcnew Sprite("./PNG/Meteors/meteorBrown_med3.png"); meteorBrown_med3->retain();
    meteorBrown_small1 = gcnew Sprite("./PNG/Meteors/meteorBrown_small1.png"); meteorBrown_small1->retain();
    meteorBrown_small2 = gcnew Sprite("./PNG/Meteors/meteorBrown_small2.png"); meteorBrown_small2->retain();
    meteorBrown_tiny1 = gcnew Sprite("./PNG/Meteors/meteorBrown_tiny1.png"); meteorBrown_tiny1->retain();
    meteorBrown_tiny2 = gcnew Sprite("./PNG/Meteors/meteorBrown_tiny2.png"); meteorBrown_tiny2->retain();
    meteorGrey_big1 = gcnew Sprite("./PNG/Meteors/meteorGrey_big1.png"); meteorGrey_big1->retain();
    meteorGrey_big2 = gcnew Sprite("./PNG/Meteors/meteorGrey_big2.png"); meteorGrey_big2->retain();
    meteorGrey_big3 = gcnew Sprite("./PNG/Meteors/meteorGrey_big3.png"); meteorGrey_big3->retain();
    meteorGrey_big4 = gcnew Sprite("./PNG/Meteors/meteorGrey_big4.png"); meteorGrey_big4->retain();
    meteorGrey_med1 = gcnew Sprite("./PNG/Meteors/meteorGrey_med1.png"); meteorGrey_med1->retain();
    meteorGrey_med2 = gcnew Sprite("./PNG/Meteors/meteorGrey_med2.png"); meteorGrey_med2->retain();
    meteorGrey_small1 = gcnew Sprite("./PNG/Meteors/meteorGrey_small1.png"); meteorGrey_small1->retain();
    meteorGrey_small2 = gcnew Sprite("./PNG/Meteors/meteorGrey_small2.png"); meteorGrey_small2->retain();
    meteorGrey_tiny1 = gcnew Sprite("./PNG/Meteors/meteorGrey_tiny1.png"); meteorGrey_tiny1->retain();
    meteorGrey_tiny2 = gcnew Sprite("./PNG/Meteors/meteorGrey_tiny2.png"); meteorGrey_tiny2->retain();
    beam0 = gcnew Sprite("./PNG/Parts/beam0.png"); beam0->retain();
    beam1 = gcnew Sprite("./PNG/Parts/beam1.png"); beam1->retain();
    beam2 = gcnew Sprite("./PNG/Parts/beam2.png"); beam2->retain();
    beam3 = gcnew Sprite("./PNG/Parts/beam3.png"); beam3->retain();
    beam4 = gcnew Sprite("./PNG/Parts/beam4.png"); beam4->retain();
    beam5 = gcnew Sprite("./PNG/Parts/beam5.png"); beam5->retain();
    beam6 = gcnew Sprite("./PNG/Parts/beam6.png"); beam6->retain();
    beamLong1 = gcnew Sprite("./PNG/Parts/beamLong1.png"); beamLong1->retain();
    beamLong2 = gcnew Sprite("./PNG/Parts/beamLong2.png"); beamLong2->retain();
    cockpitBlue_0 = gcnew Sprite("./PNG/Parts/cockpitBlue_0.png"); cockpitBlue_0->retain();
    cockpitBlue_1 = gcnew Sprite("./PNG/Parts/cockpitBlue_1.png"); cockpitBlue_1->retain();
    cockpitBlue_2 = gcnew Sprite("./PNG/Parts/cockpitBlue_2.png"); cockpitBlue_2->retain();
    cockpitBlue_3 = gcnew Sprite("./PNG/Parts/cockpitBlue_3.png"); cockpitBlue_3->retain();
    cockpitBlue_4 = gcnew Sprite("./PNG/Parts/cockpitBlue_4.png"); cockpitBlue_4->retain();
    cockpitBlue_5 = gcnew Sprite("./PNG/Parts/cockpitBlue_5.png"); cockpitBlue_5->retain();
    cockpitBlue_6 = gcnew Sprite("./PNG/Parts/cockpitBlue_6.png"); cockpitBlue_6->retain();
    cockpitBlue_7 = gcnew Sprite("./PNG/Parts/cockpitBlue_7.png"); cockpitBlue_7->retain();
    cockpitGreen_0 = gcnew Sprite("./PNG/Parts/cockpitGreen_0.png"); cockpitGreen_0->retain();
    cockpitGreen_1 = gcnew Sprite("./PNG/Parts/cockpitGreen_1.png"); cockpitGreen_1->retain();
    cockpitGreen_2 = gcnew Sprite("./PNG/Parts/cockpitGreen_2.png"); cockpitGreen_2->retain();
    cockpitGreen_3 = gcnew Sprite("./PNG/Parts/cockpitGreen_3.png"); cockpitGreen_3->retain();
    cockpitGreen_4 = gcnew Sprite("./PNG/Parts/cockpitGreen_4.png"); cockpitGreen_4->retain();
    cockpitGreen_5 = gcnew Sprite("./PNG/Parts/cockpitGreen_5.png"); cockpitGreen_5->retain();
    cockpitGreen_6 = gcnew Sprite("./PNG/Parts/cockpitGreen_6.png"); cockpitGreen_6->retain();
    cockpitGreen_7 = gcnew Sprite("./PNG/Parts/cockpitGreen_7.png"); cockpitGreen_7->retain();
    cockpitRed_0 = gcnew Sprite("./PNG/Parts/cockpitRed_0.png"); cockpitRed_0->retain();
    cockpitRed_1 = gcnew Sprite("./PNG/Parts/cockpitRed_1.png"); cockpitRed_1->retain();
    cockpitRed_2 = gcnew Sprite("./PNG/Parts/cockpitRed_2.png"); cockpitRed_2->retain();
    cockpitRed_3 = gcnew Sprite("./PNG/Parts/cockpitRed_3.png"); cockpitRed_3->retain();
    cockpitRed_4 = gcnew Sprite("./PNG/Parts/cockpitRed_4.png"); cockpitRed_4->retain();
    cockpitRed_5 = gcnew Sprite("./PNG/Parts/cockpitRed_5.png"); cockpitRed_5->retain();
    cockpitRed_6 = gcnew Sprite("./PNG/Parts/cockpitRed_6.png"); cockpitRed_6->retain();
    cockpitRed_7 = gcnew Sprite("./PNG/Parts/cockpitRed_7.png"); cockpitRed_7->retain();
    cockpitYellow_0 = gcnew Sprite("./PNG/Parts/cockpitYellow_0.png"); cockpitYellow_0->retain();
    cockpitYellow_1 = gcnew Sprite("./PNG/Parts/cockpitYellow_1.png"); cockpitYellow_1->retain();
    cockpitYellow_2 = gcnew Sprite("./PNG/Parts/cockpitYellow_2.png"); cockpitYellow_2->retain();
    cockpitYellow_3 = gcnew Sprite("./PNG/Parts/cockpitYellow_3.png"); cockpitYellow_3->retain();
    cockpitYellow_4 = gcnew Sprite("./PNG/Parts/cockpitYellow_4.png"); cockpitYellow_4->retain();
    cockpitYellow_5 = gcnew Sprite("./PNG/Parts/cockpitYellow_5.png"); cockpitYellow_5->retain();
    cockpitYellow_6 = gcnew Sprite("./PNG/Parts/cockpitYellow_6.png"); cockpitYellow_6->retain();
    cockpitYellow_7 = gcnew Sprite("./PNG/Parts/cockpitYellow_7.png"); cockpitYellow_7->retain();
    engine1 = gcnew Sprite("./PNG/Parts/engine1.png"); engine1->retain();
    engine2 = gcnew Sprite("./PNG/Parts/engine2.png"); engine2->retain();
    engine3 = gcnew Sprite("./PNG/Parts/engine3.png"); engine3->retain();
    engine4 = gcnew Sprite("./PNG/Parts/engine4.png"); engine4->retain();
    engine5 = gcnew Sprite("./PNG/Parts/engine5.png"); engine5->retain();
    gun00 = gcnew Sprite("./PNG/Parts/gun00.png"); gun00->retain();
    gun01 = gcnew Sprite("./PNG/Parts/gun01.png"); gun01->retain();
    gun02 = gcnew Sprite("./PNG/Parts/gun02.png"); gun02->retain();
    gun03 = gcnew Sprite("./PNG/Parts/gun03.png"); gun03->retain();
    gun04 = gcnew Sprite("./PNG/Parts/gun04.png"); gun04->retain();
    gun05 = gcnew Sprite("./PNG/Parts/gun05.png"); gun05->retain();
    gun06 = gcnew Sprite("./PNG/Parts/gun06.png"); gun06->retain();
    gun07 = gcnew Sprite("./PNG/Parts/gun07.png"); gun07->retain();
    gun08 = gcnew Sprite("./PNG/Parts/gun08.png"); gun08->retain();
    gun09 = gcnew Sprite("./PNG/Parts/gun09.png"); gun09->retain();
    gun10 = gcnew Sprite("./PNG/Parts/gun10.png"); gun10->retain();
    scratch1 = gcnew Sprite("./PNG/Parts/scratch1.png"); scratch1->retain();
    scratch2 = gcnew Sprite("./PNG/Parts/scratch2.png"); scratch2->retain();
    scratch3 = gcnew Sprite("./PNG/Parts/scratch3.png"); scratch3->retain();
    turretBase_big = gcnew Sprite("./PNG/Parts/turretBase_big.png"); turretBase_big->retain();
    turretBase_small = gcnew Sprite("./PNG/Parts/turretBase_small.png"); turretBase_small->retain();
    wingBlue_0 = gcnew Sprite("./PNG/Parts/wingBlue_0.png"); wingBlue_0->retain();
    wingBlue_1 = gcnew Sprite("./PNG/Parts/wingBlue_1.png"); wingBlue_1->retain();
    wingBlue_2 = gcnew Sprite("./PNG/Parts/wingBlue_2.png"); wingBlue_2->retain();
    wingBlue_3 = gcnew Sprite("./PNG/Parts/wingBlue_3.png"); wingBlue_3->retain();
    wingBlue_4 = gcnew Sprite("./PNG/Parts/wingBlue_4.png"); wingBlue_4->retain();
    wingBlue_5 = gcnew Sprite("./PNG/Parts/wingBlue_5.png"); wingBlue_5->retain();
    wingBlue_6 = gcnew Sprite("./PNG/Parts/wingBlue_6.png"); wingBlue_6->retain();
    wingBlue_7 = gcnew Sprite("./PNG/Parts/wingBlue_7.png"); wingBlue_7->retain();
    wingGreen_0 = gcnew Sprite("./PNG/Parts/wingGreen_0.png"); wingGreen_0->retain();
    wingGreen_1 = gcnew Sprite("./PNG/Parts/wingGreen_1.png"); wingGreen_1->retain();
    wingGreen_2 = gcnew Sprite("./PNG/Parts/wingGreen_2.png"); wingGreen_2->retain();
    wingGreen_3 = gcnew Sprite("./PNG/Parts/wingGreen_3.png"); wingGreen_3->retain();
    wingGreen_4 = gcnew Sprite("./PNG/Parts/wingGreen_4.png"); wingGreen_4->retain();
    wingGreen_5 = gcnew Sprite("./PNG/Parts/wingGreen_5.png"); wingGreen_5->retain();
    wingGreen_6 = gcnew Sprite("./PNG/Parts/wingGreen_6.png"); wingGreen_6->retain();
    wingGreen_7 = gcnew Sprite("./PNG/Parts/wingGreen_7.png"); wingGreen_7->retain();
    wingRed_0 = gcnew Sprite("./PNG/Parts/wingRed_0.png"); wingRed_0->retain();
    wingRed_1 = gcnew Sprite("./PNG/Parts/wingRed_1.png"); wingRed_1->retain();
    wingRed_2 = gcnew Sprite("./PNG/Parts/wingRed_2.png"); wingRed_2->retain();
    wingRed_3 = gcnew Sprite("./PNG/Parts/wingRed_3.png"); wingRed_3->retain();
    wingRed_4 = gcnew Sprite("./PNG/Parts/wingRed_4.png"); wingRed_4->retain();
    wingRed_5 = gcnew Sprite("./PNG/Parts/wingRed_5.png"); wingRed_5->retain();
    wingRed_6 = gcnew Sprite("./PNG/Parts/wingRed_6.png"); wingRed_6->retain();
    wingRed_7 = gcnew Sprite("./PNG/Parts/wingRed_7.png"); wingRed_7->retain();
    wingYellow_0 = gcnew Sprite("./PNG/Parts/wingYellow_0.png"); wingYellow_0->retain();
    wingYellow_1 = gcnew Sprite("./PNG/Parts/wingYellow_1.png"); wingYellow_1->retain();
    wingYellow_2 = gcnew Sprite("./PNG/Parts/wingYellow_2.png"); wingYellow_2->retain();
    wingYellow_3 = gcnew Sprite("./PNG/Parts/wingYellow_3.png"); wingYellow_3->retain();
    wingYellow_4 = gcnew Sprite("./PNG/Parts/wingYellow_4.png"); wingYellow_4->retain();
    wingYellow_5 = gcnew Sprite("./PNG/Parts/wingYellow_5.png"); wingYellow_5->retain();
    wingYellow_6 = gcnew Sprite("./PNG/Parts/wingYellow_6.png"); wingYellow_6->retain();
    wingYellow_7 = gcnew Sprite("./PNG/Parts/wingYellow_7.png"); wingYellow_7->retain();
    playerShip1_blue = gcnew Sprite("./PNG/playerShip1_blue.png"); playerShip1_blue->retain();
    playerShip1_green = gcnew Sprite("./PNG/playerShip1_green.png"); playerShip1_green->retain();
    playerShip1_orange = gcnew Sprite("./PNG/playerShip1_orange.png"); playerShip1_orange->retain();
    playerShip1_red = gcnew Sprite("./PNG/playerShip1_red.png"); playerShip1_red->retain();
    playerShip2_blue = gcnew Sprite("./PNG/playerShip2_blue.png"); playerShip2_blue->retain();
    playerShip2_green = gcnew Sprite("./PNG/playerShip2_green.png"); playerShip2_green->retain();
    playerShip2_orange = gcnew Sprite("./PNG/playerShip2_orange.png"); playerShip2_orange->retain();
    playerShip2_red = gcnew Sprite("./PNG/playerShip2_red.png"); playerShip2_red->retain();
    playerShip3_blue = gcnew Sprite("./PNG/playerShip3_blue.png"); playerShip3_blue->retain();
    playerShip3_green = gcnew Sprite("./PNG/playerShip3_green.png"); playerShip3_green->retain();
    playerShip3_orange = gcnew Sprite("./PNG/playerShip3_orange.png"); playerShip3_orange->retain();
    playerShip3_red = gcnew Sprite("./PNG/playerShip3_red.png"); playerShip3_red->retain();
    bold_silver = gcnew Sprite("./PNG/Power-ups/bold_silver.png"); bold_silver->retain();
    bolt_bronze = gcnew Sprite("./PNG/Power-ups/bolt_bronze.png"); bolt_bronze->retain();
    bolt_gold = gcnew Sprite("./PNG/Power-ups/bolt_gold.png"); bolt_gold->retain();
    pill_blue = gcnew Sprite("./PNG/Power-ups/pill_blue.png"); pill_blue->retain();
    pill_green = gcnew Sprite("./PNG/Power-ups/pill_green.png"); pill_green->retain();
    pill_red = gcnew Sprite("./PNG/Power-ups/pill_red.png"); pill_red->retain();
    pill_yellow = gcnew Sprite("./PNG/Power-ups/pill_yellow.png"); pill_yellow->retain();
    powerupBlue = gcnew Sprite("./PNG/Power-ups/powerupBlue.png"); powerupBlue->retain();
    powerupBlue_bolt = gcnew Sprite("./PNG/Power-ups/powerupBlue_bolt.png"); powerupBlue_bolt->retain();
    powerupBlue_shield = gcnew Sprite("./PNG/Power-ups/powerupBlue_shield.png"); powerupBlue_shield->retain();
    powerupBlue_star = gcnew Sprite("./PNG/Power-ups/powerupBlue_star.png"); powerupBlue_star->retain();
    powerupGreen = gcnew Sprite("./PNG/Power-ups/powerupGreen.png"); powerupGreen->retain();
    powerupGreen_bolt = gcnew Sprite("./PNG/Power-ups/powerupGreen_bolt.png"); powerupGreen_bolt->retain();
    powerupGreen_shield = gcnew Sprite("./PNG/Power-ups/powerupGreen_shield.png"); powerupGreen_shield->retain();
    powerupGreen_star = gcnew Sprite("./PNG/Power-ups/powerupGreen_star.png"); powerupGreen_star->retain();
    powerupRed = gcnew Sprite("./PNG/Power-ups/powerupRed.png"); powerupRed->retain();
    powerupRed_bolt = gcnew Sprite("./PNG/Power-ups/powerupRed_bolt.png"); powerupRed_bolt->retain();
    powerupRed_shield = gcnew Sprite("./PNG/Power-ups/powerupRed_shield.png"); powerupRed_shield->retain();
    powerupRed_star = gcnew Sprite("./PNG/Power-ups/powerupRed_star.png"); powerupRed_star->retain();
    powerupYellow = gcnew Sprite("./PNG/Power-ups/powerupYellow.png"); powerupYellow->retain();
    powerupYellow_bolt = gcnew Sprite("./PNG/Power-ups/powerupYellow_bolt.png"); powerupYellow_bolt->retain();
    powerupYellow_shield = gcnew Sprite("./PNG/Power-ups/powerupYellow_shield.png"); powerupYellow_shield->retain();
    powerupYellow_star = gcnew Sprite("./PNG/Power-ups/powerupYellow_star.png"); powerupYellow_star->retain();
    shield_bronze = gcnew Sprite("./PNG/Power-ups/shield_bronze.png"); shield_bronze->retain();
    shield_gold = gcnew Sprite("./PNG/Power-ups/shield_gold.png"); shield_gold->retain();
    shield_silver = gcnew Sprite("./PNG/Power-ups/shield_silver.png"); shield_silver->retain();
    star_bronze = gcnew Sprite("./PNG/Power-ups/star_bronze.png"); star_bronze->retain();
    star_gold = gcnew Sprite("./PNG/Power-ups/star_gold.png"); star_gold->retain();
    star_silver = gcnew Sprite("./PNG/Power-ups/star_silver.png"); star_silver->retain();
    things_bronze = gcnew Sprite("./PNG/Power-ups/things_bronze.png"); things_bronze->retain();
    things_gold = gcnew Sprite("./PNG/Power-ups/things_gold.png"); things_gold->retain();
    things_silver = gcnew Sprite("./PNG/Power-ups/things_silver.png"); things_silver->retain();
    ufoBlue = gcnew Sprite("./PNG/ufoBlue.png"); ufoBlue->retain();
    ufoGreen = gcnew Sprite("./PNG/ufoGreen.png"); ufoGreen->retain();
    ufoRed = gcnew Sprite("./PNG/ufoRed.png"); ufoRed->retain();
    ufoYellow = gcnew Sprite("./PNG/ufoYellow.png"); ufoYellow->retain();
    aim = gcnew Sprite("./PNG/UI/aim.png"); aim->retain();
    buttonBlue = gcnew Sprite("./PNG/UI/buttonBlue.png"); buttonBlue->retain();
    buttonGreen = gcnew Sprite("./PNG/UI/buttonGreen.png"); buttonGreen->retain();
    buttonRed = gcnew Sprite("./PNG/UI/buttonRed.png"); buttonRed->retain();
    buttonYellow = gcnew Sprite("./PNG/UI/buttonYellow.png"); buttonYellow->retain();
    cursor = gcnew Sprite("./PNG/UI/cursor.png"); cursor->retain();
    numeral0 = gcnew Sprite("./PNG/UI/numeral0.png"); numeral0->retain();
    numeral1 = gcnew Sprite("./PNG/UI/numeral1.png"); numeral1->retain();
    numeral2 = gcnew Sprite("./PNG/UI/numeral2.png"); numeral2->retain();
    numeral3 = gcnew Sprite("./PNG/UI/numeral3.png"); numeral3->retain();
    numeral4 = gcnew Sprite("./PNG/UI/numeral4.png"); numeral4->retain();
    numeral5 = gcnew Sprite("./PNG/UI/numeral5.png"); numeral5->retain();
    numeral6 = gcnew Sprite("./PNG/UI/numeral6.png"); numeral6->retain();
    numeral7 = gcnew Sprite("./PNG/UI/numeral7.png"); numeral7->retain();
    numeral8 = gcnew Sprite("./PNG/UI/numeral8.png"); numeral8->retain();
    numeral9 = gcnew Sprite("./PNG/UI/numeral9.png"); numeral9->retain();
    numeralX = gcnew Sprite("./PNG/UI/numeralX.png"); numeralX->retain();
    playerLife1_blue = gcnew Sprite("./PNG/UI/playerLife1_blue.png"); playerLife1_blue->retain();
    playerLife1_green = gcnew Sprite("./PNG/UI/playerLife1_green.png"); playerLife1_green->retain();
    playerLife1_orange = gcnew Sprite("./PNG/UI/playerLife1_orange.png"); playerLife1_orange->retain();
    playerLife1_red = gcnew Sprite("./PNG/UI/playerLife1_red.png"); playerLife1_red->retain();
    playerLife2_blue = gcnew Sprite("./PNG/UI/playerLife2_blue.png"); playerLife2_blue->retain();
    playerLife2_green = gcnew Sprite("./PNG/UI/playerLife2_green.png"); playerLife2_green->retain();
    playerLife2_orange = gcnew Sprite("./PNG/UI/playerLife2_orange.png"); playerLife2_orange->retain();
    playerLife2_red = gcnew Sprite("./PNG/UI/playerLife2_red.png"); playerLife2_red->retain();
    playerLife3_blue = gcnew Sprite("./PNG/UI/playerLife3_blue.png"); playerLife3_blue->retain();
    playerLife3_green = gcnew Sprite("./PNG/UI/playerLife3_green.png"); playerLife3_green->retain();
    playerLife3_orange = gcnew Sprite("./PNG/UI/playerLife3_orange.png"); playerLife3_orange->retain();
    playerLife3_red = gcnew Sprite("./PNG/UI/playerLife3_red.png"); playerLife3_red->retain();
    particle1_blue = gcnew Sprite("./PNG/Particle/particle1_blue.png"); particle1_blue->retain();
    particle1_green = gcnew Sprite("./PNG/Particle/particle1_green.png"); particle1_green->retain();
    particle1_red = gcnew Sprite("./PNG/Particle/particle1_red.png"); particle1_red->retain();
    particle1_white = gcnew Sprite("./PNG/Particle/particle1_white.png"); particle1_white->retain();
    particle1_yellow = gcnew Sprite("./PNG/Particle/particle1_yellow.png"); particle1_yellow->retain();
}